@url=http://localhost:8080/categories

###
POST {{url}}/categories
Content-Type: application/json

{
    "name": "Produtos de limpeza"
}

###
GET {{url}}/65c127a4e7f6690e1a114f12

###
PUT {{url}}/65c127a4e7f6690e1a114f12
Content-Type: application/json

{
    "name": "Tecnologias"
}

###
DELETE {{url}}/65c127a4e7f6690e1a114f12