@url=http://localhost:8080/users

### list all users
GET {{url}}

###
GET {{url}}/65c4d46bbbfbc568d87478c7

###
POST {{url}}/users
Content-Type: application/json

{
    "name": "Alex grey",
    "password": "alex123",
    "email": "alexgrey@hotmail.com",
    "document": "123.123.123-33"
}

###
PUT {{url}}/users/65c4c0c3c82f515c6a777625
Content-Type: application/json

{
    "name": "Alex grey2",
    "password": "alex123",
    "email": "alexgrey@hotmail.com",
    "document": "123.123.123-33"
}

###
DELETE  {{url}}/users/65c122e0e7f6690e1a114ee8